### ISSUE TITLE
Error ELIFECYCLE with error 1 in `npm run build`

### ISSUE THREAD

**Issue by glloyd0314** [yodhcn/dlsite-play#1]
Sorry to interrupt.  Here is the `build` problem I met while building the project. (`serve` and `lint` work fine)
The project folder is gited to the directory `/root/dlsite-play` and installed without errors.
I then run the code `npm run build` with user `root` and the terminal gives me the information as below:
 - Part 1
```
⠇  Building for production...

 ERROR  Failed to compile with 1 errors                               2:13:34 AM

 error  in ./node_modules/lodash/LICENSE

Module Error (from ./node_modules/html-loader/dist/cjs.js):
Parse Error: <https://openjsf.org/>

Based on Underscore.js, copyright Jeremy Ashkenas,
DocumentCloud and Investigative Reporters & Editors <http://underscorejs.org/>
```
 - Part 2
```
 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dlsite-play@5.0.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dlsite-play@5.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-07T17_13_34_351Z-debug.log
```
And the log shows:
```
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v10.20.1/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v10.20.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.14.4
3 info using node@v10.20.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle dlsite-play@5.0.0~prebuild: dlsite-play@5.0.0
6 info lifecycle dlsite-play@5.0.0~build: dlsite-play@5.0.0
7 verbose lifecycle dlsite-play@5.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle dlsite-play@5.0.0~build: PATH: /root/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/dlsite-play/node_modules/.bin:/root/.nvm/versions/node/v10.20.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle dlsite-play@5.0.0~build: CWD: /root/dlsite-play
10 silly lifecycle dlsite-play@5.0.0~build: Args: [ '-c', 'vue-cli-service build' ]
11 silly lifecycle dlsite-play@5.0.0~build: Returned: code: 1  signal: null
12 info lifecycle dlsite-play@5.0.0~build: Failed to exec build script
13 verbose stack Error: dlsite-play@5.0.0 build: `vue-cli-service build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.20.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid dlsite-play@5.0.0
15 verbose cwd /root/dlsite-play
16 verbose Linux 4.4.0-47-generic
17 verbose argv "/root/.nvm/versions/node/v10.20.1/bin/node" "/root/.nvm/versions/node/v10.20.1/bin/npm" "run" "build"
18 verbose node v10.20.1
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error dlsite-play@5.0.0 build: `vue-cli-service build`
22 error Exit status 1
23 error Failed at the dlsite-play@5.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Again sorry for using your time. It does confuse me for several hours while I check all the internet about the error code without solving the problem.
Hope to hear from you and thank you in advance!

**Comment by yodhcn** [comment]
这可能是因为我错误地使用了 `raw-loader`
在我改用 `raw-loader` 加载 LICENSE 后，`npm run build` 就不会再报错了。
